# Generated by Django 3.0.7 on 2020-11-17 15:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
from django.utils import timezone

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('email', models.EmailField(max_length=50,primary_key=True)),
                ('name', models.CharField(max_length=50)),
                ('message', models.TextField(max_length=500)),
                ('time', models.DateTimeField(default=timezone.now())),
            ],
        ),
    ]
