# Generated by Django 3.0.7 on 2020-11-18 06:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20201118_0457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 18, 6, 6, 28, 996819, tzinfo=utc)),
        ),
    ]
