# Generated by Django 3.1.2 on 2020-11-23 12:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20201123_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 23, 12, 2, 36, 652763, tzinfo=utc)),
        ),
    ]
