# Generated by Django 3.1.2 on 2020-11-23 19:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20201123_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 23, 19, 47, 57, 653464, tzinfo=utc)),
        ),
    ]
