# Generated by Django 3.1.2 on 2020-11-23 21:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20201124_0158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 23, 21, 16, 18, 142160, tzinfo=utc)),
        ),
    ]
