# Generated by Django 3.1.2 on 2020-11-23 21:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_auto_20201124_0246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 23, 21, 36, 47, 744897, tzinfo=utc)),
        ),
    ]
