# Generated by Django 3.1.2 on 2020-11-24 10:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_auto_20201124_0306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 24, 10, 29, 35, 453437, tzinfo=utc)),
        ),
    ]
