# Generated by Django 3.1.2 on 2020-11-24 19:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_auto_20201124_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 24, 19, 8, 0, 996372, tzinfo=utc)),
        ),
    ]
