# Generated by Django 3.1.2 on 2020-11-25 19:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_auto_20201126_0109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 25, 19, 41, 16, 472663, tzinfo=utc)),
        ),
    ]
