# Generated by Django 3.1.2 on 2020-11-26 08:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_auto_20201126_0111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 26, 8, 16, 6, 888530, tzinfo=utc)),
        ),
    ]
