# Generated by Django 3.1.2 on 2020-11-24 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20201124_1600'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='register',
            new_name='email',
        ),
    ]
