# Generated by Django 3.1.2 on 2020-11-25 11:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_auto_20201125_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 25, 11, 44, 45, 696398, tzinfo=utc)),
        ),
    ]
