# Generated by Django 3.1.2 on 2020-11-25 19:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_auto_20201125_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
